### ISSUE TITLE
Validation missing for selectors not matching layers

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#29]
This works without warning or error if #foo is not a valid layer.

<pre>
#foo {
  bar:bar
}
</pre>

**Comment by nebulon42** [comment]
We have now warnings when a layer has no associated styles and when styles do not match a corresponding layer selector.

The following situation (taken from osm-carto):
```
#admin-low-zoom[zoom < 11],
#admin-mid-zoom[zoom >= 11][zoom < 13],
#admin-high-zoom[zoom >= 13] {
  [admin_level = '4'] {
    [zoom >= 12] {
      background/line-width: 3;
      line-width: 3;
    }
  }
}
```
generates a warning about styles not matching the layer selector #admin-low-zoom. This is because #admin-low-zoom is filtered only for zooms < 11. The warning is correct but this code is also legit. We should figure out a way if we could suppress this kind of warnings because they are likely to create some noise.

**Comment by nebulon42** [comment]
As for the other error report: Currently rules are only validated upon serializing them to XML. I'm not sure if it is worth to change that.

**Comment by nebulon42** [comment]
I think it does not make sense to delay 1.0 any longer because of https://github.com/mapbox/carto/issues/29#issuecomment-304509299.
