### ISSUE TITLE
Support modulo in selectors

### ISSUE THREAD

**Issue by systemed** [mapbox/carto#377]
Mapnik supports the numeric modulo (%) operator in selectors: https://github.com/mapnik/mapnik/wiki/Filter#examples-in-xml

For example:

```
<Filter>[height] % 50 = 0</Filter> 
```

Carto support for this would be good.

**Comment by springmeyer** [comment]
@systemed would 9459084 work?

**Comment by systemed** [comment]
Looks great.

**Comment by pnorman** [comment]
Was a PR ever done for the branch @springmeyer did?

**Comment by nebulon42** [comment]
No, because the syntax is a bit incomplete. When you are only able to specify x % 2 without anything else it is unclear what you are filtering for.

**Comment by gravitystorm** [comment]
I've run into the need for this too. I think @nebulon42 is correct about the suggested patch - it makes something like this work:

```
<Filter>[height] % 50</Filter> 
```
whereas what we want is slightly different:
```
<Filter>[height] % 50 = 0</Filter> 
```
The latter is the example used in the [mapnik documenation for filters](https://github.com/mapnik/mapnik/wiki/Filter).

As far as I can figure out, the problem seems to be in [carto's parsing of the filter](https://github.com/mapbox/carto/blob/f37bd50ee1c62f2456ffccd350d1943a4a876e7c/lib/carto/parser.js#L542). It expects to see something like `key operator value`. In our example modulo is part of the key, not an operator. So I think we want to end up with:

* `[height] % 50` is the key 
* `=` is the operator
* `0` is the value

I can't figure out if one of the [existing five tests](https://github.com/mapbox/carto/blob/f37bd50ee1c62f2456ffccd350d1943a4a876e7c/lib/carto/parser.js#L548-L552) for keys should be modified to allow the above, or a sixth test added. Any guidance on the right approach would be welcome - I'm a bit out of my depth here.

**Comment by gravitystorm** [comment]
I tried adding `this.expression` to the list of key tests, and while that made it pass this example, it broke 40+ other tests :-(

**Comment by nebulon42** [comment]
If we allow expressions in filters we might have to start writing fields explicitly with `[field]` syntax. When changing https://github.com/mapbox/carto/blob/f37bd50ee1c62f2456ffccd350d1943a4a876e7c/lib/carto/parser.js#L548 to `$(this.expression)` the failing tests complain about keywords. So the parsers does not recognize height in `height = 0` as field anymore. Writing `[height] = 0` fixes that.

But I only had a quick look. Maybe there is a better alternative.

**Comment by nebulon42** [comment]
One has the be careful in which order the expression is added for the parser. Seems to work now, only restriction is that field references have to be properly written within brackets e.g. `[[height] % 50 = 0]`.
