### ISSUE TITLE
Less variables in URLs

### ISSUE THREAD

**Issue by Xevib** [mapbox/carto#387]
Less specifies that you can use variables in url , this will be useful to setup a directory of images
Example:
http://lesscss.org/features/#variables-feature-urls

**Comment by tmcw** [comment]
Less has an in-browser interpreter, so this makes sense. Carto doesn't, and the way that it's used doesn't open up much room to implement this - the raster tiles you make with TileMill are pre-baked. You can provide [variables to the parser](https://github.com/mapbox/carto/blob/master/lib/carto/parser.js#L8) via the JavaScript API if you're integrating on the node level, but otherwise, this is a wont-fix because Carto has no guarantee of a URL being part of its workflow at all.
